### ISSUE TITLE
Cannot build on stable (similar to issue #226)

### ISSUE THREAD

**Issue by antimora** [Lokathor/bytemuck#328]
It appears that the crate cannot be built on stable Rust. This looks similar to the issue discussed in #226.

**Problem:**
- Build fails on stable Rust due to usage of unstable library features (`stdsimd`, etc.).
- Error messages and context seem similar to those described in [issue #226](https://github.com/Lokathor/bytemuck/issues/226).

**Steps to reproduce:**
1. Attempt to build the crate on stable Rust.
2. Observe compilation errors related to unstable features.

**Expected behavior:**
- The crate should build successfully on stable Rust, or appropriate gating/features should be documented.

**Reference:**
- #226: https://github.com/Lokathor/bytemuck/issues/226

```
   Compiling synstructure v0.13.2
error[E0658]: use of unstable library feature `stdarch_x86_avx512`
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytemuck-1.24.0/src/lib.rs:153:28
    |
153 |       unsafe impl $trait for $platform::$first_type {}
    |                              ^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytemuck-1.24.0/src/zeroable.rs:258:1
    |
258 | / impl_unsafe_marker_for_simd!(
259 | |   #[cfg(all(target_arch = "x86_64", feature = "avx512_simd"))]
260 | |   unsafe impl Zeroable for x86_64::{
261 | |     __m128bh, __m256bh, __m512bh
262 | |   }
263 | | );
    | |_- in this macro invocation
    |
    = note: see issue #111137 <https://github.com/rust-lang/rust/issues/111137> for more information
    = note: this error originates in the macro `impl_unsafe_marker_for_simd` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature `stdarch_x86_avx512`
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytemuck-1.24.0/src/lib.rs:153:28
    |
153 |       unsafe impl $trait for $platform::$first_type {}
    |                              ^
    |
   ::: /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytemuck-1.24.0/src/zeroable.rs:258:1
    |
258 | / impl_unsafe_marker_for_simd!(
259 | |   #[cfg(all(target_arch = "x86_64", feature = "avx512_simd"))]
260 | |   unsafe impl Zeroable for x86_64::{
261 | |     __m128bh, __m256bh, __m512bh
262 | |   }
263 | | );
    | |_- in this macro invocation
    |
    = note: see issue #111137 <https://github.com/rust-lang/rust/issues/111137> for more information
    = note: this error originates in the macro `impl_unsafe_marker_for_simd` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature `stdarch_x86_avx512`
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytemuck-1.24.0/src/lib.rs:153:28
    |
153 |       unsafe impl $trait for $platform::$first_type {}
    |                              ^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytemuck-1.24.0/src/pod.rs:179:1
    |
179 | / impl_unsafe_marker_for_simd!(
180 | |     #[cfg(all(target_arch = "x86_64", feature = "avx512_simd"))]
181 | |   unsafe impl Pod for x86_64::{
182 | |     __m128bh, __m256bh, __m512bh
183 | |   }
184 | | );
    | |_- in this macro invocation
    |
    = note: see issue #111137 <https://github.com/rust-lang/rust/issues/111137> for more information
    = note: this error originates in the macro `impl_unsafe_marker_for_simd` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature `stdarch_x86_avx512`
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytemuck-1.24.0/src/lib.rs:153:28
    |
153 |       unsafe impl $trait for $platform::$first_type {}
    |                              ^
    |
   ::: /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytemuck-1.24.0/src/pod.rs:179:1
    |
179 | / impl_unsafe_marker_for_simd!(
180 | |     #[cfg(all(target_arch = "x86_64", feature = "avx512_simd"))]
181 | |   unsafe impl Pod for x86_64::{
182 | |     __m128bh, __m256bh, __m512bh
183 | |   }
184 | | );
    | |_- in this macro invocation
    |
    = note: see issue #111137 <https://github.com/rust-lang/rust/issues/111137> for more information
    = note: this error originates in the macro `impl_unsafe_marker_for_simd` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bytemuck` (lib) due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Workspace Unit Tests failed (exit status: 101)
Error: Process completed with exit code 1.
```

**Comment by Lokathor** [comment]
This repo's CI says the crate builds on 1.34, 1.61, and Stable (1.90). Are you sure that somewhere in the build tree there isn't a crate activating bytemuck's nightly features by mistake?

**Comment by Lokathor** [comment]
I can't tell what crate features you end up using based on that log and your Cargo.toml, but **I suspect** that somewhere in your build graph someone is using the `latest_stable_rust` crate feature. Because you're on 1.88, which isn't the latest stable version of rust, using the `latest_stable_rust` crate feature would naturally cause you a problem.

https://github.com/Lokathor/bytemuck/blob/main/Cargo.toml#L75
