### PR TITLE
Make `AnyBitPattern` derive work for generic structs

### PR DESCRIPTION
**Pull request by cky**
(Note: despite the similar titles, this PR is not related to #83 at all. This PR is specific to the changes introduced in #91.)

When using `AnyBitPattern` derive, an automatic derive for `Zeroable` is created as well. However, the latter derive is missing generic parameters for the struct, which means you get errors like the following:

```
error[E0107]: missing generics for struct `AnyBitPatternTest`
   --> tests/basic.rs:107:8
    |
107 | struct AnyBitPatternTest<A: AnyBitPattern, B: AnyBitPattern> {
    |        ^^^^^^^^^^^^^^^^^ expected 2 generic arguments
    |
note: struct defined here, with 2 generic parameters: `A`, `B`
   --> tests/basic.rs:107:8
    |
107 | struct AnyBitPatternTest<A: AnyBitPattern, B: AnyBitPattern> {
    |        ^^^^^^^^^^^^^^^^^ -                 -
help: add missing generic arguments
    |
107 | struct AnyBitPatternTest<A, B><A: AnyBitPattern, B: AnyBitPattern> {
    |        ~~~~~~~~~~~~~~~~~~~~~~~
```

The help text is worse than useless, because the suggested fix makes things worse.

### CODE REVIEW

**Comment by Lokathor** [comment]
@fu5ha you get to review this one!

**Review by fu5ha — APPROVED** [review]
lgtm :)

**Comment by fu5ha** [comment]
Not sure why this is failing on nightly tho

**Comment by cky** [comment]
Wonder if it's using the old macro expansion? Certainly the error message suggests so. Didn't you run into similar CI bogosity in #91?

**Comment by cky** [comment]
Just so I know I haven't gone nuts, here's the nightly and miri runs on my computer: https://gist.github.com/cky/f80cc8b82632bd10deaebcb1a5668172

**Comment by cky** [comment]
Is there a way to rerun the CI? I could technically push an empty commit just to trigger one but if there's a way to actually just rerun, I'd rather not junk up the branch with empty commits. ;-)

**Comment by Lokathor** [comment]
I'll try a close and re-open.
